server:
  port: 9999
  servlet:
    context-path: /api
  #session 配置
  session:
    timeout: 1800 #30 min过期
spring:
  application:
    name: prodigal-system
  profiles:
    # 本地环境配置
    active: ${SPRING_PROFILES_ACTIVE:local}
